### PR TITLE
Replace Object type by correct types

### PR DESCRIPTION
**Pull request by etienneCharignon**
You might have set types as Object on purpose, however I found it misleading about the purpose of the exercice.

What do you think about changing types by there correct value ?

### CODE REVIEW

**Comment by konohiroaki** [comment]
Hi etienneCharignon, thank you for your suggestion!
Yes, actually that was on purpose. The reason I wrote Object type is because I wanted to give less hint. Also this is applied to many other files as well. For these two reasons I prefer keeping it as it is.
However your concern is also understandable because I didn't mention that that part should also be corrected. But I cannot come up with nice solution for this. Mentioning it on each tests are horrible. Maybe mentioning it on the README is possible. What do you think?

**Comment by etienneCharignon** [comment]
You could à a comment only in the first test of the first exercise. That’s the moment when the « player » is wondering how the exercise works. 

In the reader would be too far from there, I think. 

What about replacing Object by two or three question marks ? 

ˋConsumer<???>ˋ

**Comment by konohiroaki** [comment]
> What about replacing Object by two or three question marks ?

This won't be a valid Java code, so it will disrupt people who wants to run the test before completing everything (because Compile Error occurs). 

> You could à a comment only in the first test of the first exercise.

Yes that might be a nice solution. Would you like me to apply this change?

**Comment by konohiroaki** [comment]
Since I'm not getting any response for a month, I will close this PR. The change will not be applied.

**Comment by etienneCharignon** [comment]
Ok, that's fine. I'm sorry about that. The action stayed all that time in ma todo list without finding any way out. I might still find some time one day but I agree that is more reasonable to close it for now.

**Pull request closed without merging**
